<script lang="ts">
	import ReportPrintout from '$lib/ui/components/print/ReportPrintout.svelte';
	import { basisLabel, describeRate } from '$lib/utilities/incentives';
	import type { PageData } from './$types';

	let {
		report,
		items,
		period,
		coverage,
		filters,
		prepared_by,
		generated_by
	}: {
		report: PageData['report'];
		items: PageData['items'];
		period: string;
		coverage: string;
		filters: string;
		prepared_by: { name: string; role: string };
		generated_by: string;
	} = $props();

	const peso = new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' });
	const count = (v: number) => v.toLocaleString('en-PH');
	const formatDate = (d: string) =>
		new Date(d).toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric' });

	const visible = $derived(new Set(report.by_group.map((g) => g.group)));
	const person = $derived(new Map(report.by_recipient.map((r) => [r.user, r.name])));
	const group_name = $derived(new Map(report.group_settings.map((g) => [g.group, g.name])));
</script>

<ReportPrintout
	title={`Incentive Report ${report.reference_no}`}
	{period}
	{coverage}
	{filters}
	{prepared_by}
>
	{#if report.status === 'voided'}
		<p class="rp-notice">
			<strong>VOIDED.</strong> This report was voided by {report.voided_by_name || 'unknown'}: “{report.void_reason}”.
			It must not be used for payout.
		</p>
	{/if}

	<p class="rp-muted">
		Generated by {generated_by}{report.remarks ? ` · Remarks: ${report.remarks}` : ''}
	</p>

	<h2 class="rp-h2">Summary</h2>
	<dl class="rp-figures">
		<div>
			<dt>Tickets</dt>
			<dd>{count(report.totals.ticket_count)}</dd>
		</div>
		<div>
			<dt>Officers</dt>
			<dd>{count(report.totals.recipient_count)}</dd>
		</div>
		<div>
			<dt>Base amount</dt>
			<dd>{peso.format(report.totals.base_amount)}</dd>
		</div>
		<div>
			<dt>Total incentive</dt>
			<dd>{peso.format(report.totals.incentive_amount)}</dd>
		</div>
	</dl>

	<h2 class="rp-h2">Rates used</h2>
	<table class="rp-table">
		<thead>
			<tr>
				<th>Group</th>
				<th>Rate applied</th>
				<th>Saved setting / reason for change</th>
				<th class="rp-num">Tickets</th>
				<th class="rp-num">Incentive</th>
			</tr>
		</thead>
		<tbody>
			{#each report.group_settings.filter((g) => visible.has(g.group)) as g (g.group)}
				{@const totals = report.by_group.find((x) => x.group === g.group)}
				<tr>
					<td>{g.name}</td>
					<td>{describeRate(g.applied, peso)} · {basisLabel(g.applied.basis)}</td>
					<td>
						{#if g.overridden}
							Changed from {g.defaults
								? `${describeRate(g.defaults, peso)}${g.defaults_enabled ? '' : ' (off)'}`
								: 'no saved rate'} — {g.override_reason}
						{:else}
							Same as saved
						{/if}
					</td>
					<td class="rp-num">{count(totals?.ticket_count ?? 0)}</td>
					<td class="rp-num">{peso.format(totals?.incentive_amount ?? 0)}</td>
				</tr>
			{/each}
		</tbody>
	</table>

	<h2 class="rp-h2">Payout by officer</h2>
	<table class="rp-table">
		<thead>
			<tr>
				<th class="rp-index">#</th>
				<th>Officer</th>
				<th>Group</th>
				<th class="rp-num">Tickets</th>
				<th class="rp-num">Base</th>
				<th class="rp-num">Incentive</th>
				<th>Received by</th>
			</tr>
		</thead>
		<tbody>
			{#each report.by_recipient as r, index (`${r.group}:${r.user}`)}
				<tr>
					<td class="rp-index">{index + 1}</td>
					<td>{r.name}{r.user_type ? ` (${r.user_type})` : ''}</td>
					<td>{group_name.get(r.group) ?? ''}</td>
					<td class="rp-num">{count(r.ticket_count)}</td>
					<td class="rp-num">{peso.format(r.base_amount)}</td>
					<td class="rp-num">{peso.format(r.incentive_amount)}</td>
					<td style="min-width: 90pt"></td>
				</tr>
			{:else}
				<tr><td colspan="7" class="rp-empty">No officers in this report.</td></tr>
			{/each}
			{#if report.by_recipient.length}
				<tr class="rp-total">
					<td></td>
					<td colspan="2">Total</td>
					<td class="rp-num">{count(report.totals.ticket_count)}</td>
					<td class="rp-num">{peso.format(report.totals.base_amount)}</td>
					<td class="rp-num">{peso.format(report.totals.incentive_amount)}</td>
					<td></td>
				</tr>
			{/if}
		</tbody>
	</table>

	{#if report.exclusions.length}
		<h2 class="rp-h2">Tickets left out <small>· {report.exclusions.length}</small></h2>
		<table class="rp-table rp-list">
			<thead>
				<tr>
					<th>Tracking code</th>
					<th>Officer</th>
					<th>Reason</th>
				</tr>
			</thead>
			<tbody>
				{#each report.exclusions as ex (ex.issuance)}
					<tr>
						<td class="rp-code">{ex.tracking_code}</td>
						<td>{(ex.issuer && person.get(ex.issuer)) || ''}</td>
						<td>{ex.reason}</td>
					</tr>
				{/each}
			</tbody>
		</table>
	{/if}

	<h2 class="rp-h2">Tickets counted <small>· {count(items.length)}</small></h2>
	<table class="rp-table rp-list">
		<thead>
			<tr>
				<th class="rp-index">#</th>
				<th>Tracking code</th>
				<th>Officer</th>
				<th>Counted on</th>
				<th class="rp-num">Base</th>
				<th class="rp-num">Incentive</th>
			</tr>
		</thead>
		<tbody>
			{#each items as item, index (item._id)}
				<tr>
					<td class="rp-index">{index + 1}</td>
					<td class="rp-code">{item.tracking_code}</td>
					<td>{person.get(item.issuer) ?? ''}</td>
					<td class="rp-nowrap">
						{formatDate(item.event_date)} ({item.basis === 'paid' ? 'paid' : 'issued'})
					</td>
					<td class="rp-num">{peso.format(item.base_amount)}</td>
					<td class="rp-num">{peso.format(item.incentive_amount)}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</ReportPrintout>
